# Generated by Django 4.0.3 on 2022-03-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='manu',
            new_name='menu',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
