# Generated by Django 4.0.3 on 2022-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_manu_category_menu_alter_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
